Improvements to `EitherOrBoth`
rust-itertools/itertools pull request #629
Opened 2022-07-04 23:41 UTC by JoJoJet

* Added more methods for accessing the left and right variants.
* Added methods for inserting left and right values (using unsafe code).
* Fixed clippy lints.
* Improved some grammar.

2022-07-06 21:07 UTC, phimuemue commented
Hi there, thanks for addressing the compilation issues.

Could you rebase the changes so we do not need to review back-and-forth changes?

2022-07-07 04:21 UTC, JoJoJet commented
> Could you rebase the changes so we do not need to review back-and-forth changes?

Done, I think.

2023-05-20 23:15 UTC, oxalica requested changes

2023-05-20 23:15 UTC, oxalica commented on src/either_or_both.rs
> +    pub fn into_left(self) -> A
I prefer `left_biased`, which implies the fallback behavior on `Right`. So does `into_right` -> `right_biased`.
This `*_biased` wording is also used by `rowan`, the parser library of `rust-analyzer`, in an enum like our `EitherOrBoth` but allows empty.
https://docs.rs/rowan/0.15.11/rowan/enum.TokenAtOffset.html#method.left_biased

2023-05-21 12:42 UTC, oxalica commented on src/either_or_both.rs
> +    pub fn into_left(self) -> A
> I don't think that the `*_biased` naming convention really captures what's going on here.

To my intuition, `left_biased` implies that "prefer Left, but fallback to return Right if there's no Left". `into_left` sounds like "we know there's a Left inside, just unwrap it" (like `into_inner`?).
But you're right, there's a conversion when `Right(_)` is encountered, and `into_left` captures this behavior.

2023-06-14 21:15 UTC, jswrenn approved these changes
bors r+

2023-06-14 21:18 UTC, merged