feat: add combinations_up_to
rust-itertools/itertools pull request #687
Opened 2023-03-24 09:41 UTC by maratik123

2023-06-14 14:48 UTC, jswrenn requested changes

2023-06-14 14:48 UTC, jswrenn commented on src/lib.rs
> +    /// ]);
I wonder if the name `combinations_up_to` is perhaps a little misleading, since the combinations are emitted in _descending_ order of size.

2023-06-14 14:48 UTC, jswrenn commented on src/combinations_up_to.rs
> +            }
Do you think we can get rid of the `end` field by checking if `self.iter.k() == 0`?

2023-06-17 11:03 UTC, Philippe-Cholet commented
I think the name `combinations_up_to` is nice. What's weird for me is that it starts with "k" items then decrease instead of starting with 0 items then increase, that would feel more natural, something like: `vec![], vec![1], vec![2], vec![3], vec![4], vec![1, 2], vec![1, 3], ...` which is not even the reverse order of the current behavior.
Then maybe we could impl DoubleEndedIterator for it.

2023-07-18 23:43 UTC, maratik123 commented
> EDIT: Currently I think it's something like `(0..=k).rev().flat_map(|i| iter.clone().combinations(i))`. Is that needed?

Yes, agree with you. Seems that this PR is not needed. Closing it now.

2023-07-18 23:44 UTC, closed without merging