`TupleCombinations`: `size_hint` and `count`
rust-itertools/itertools pull request #763
Opened 2023-09-27 16:53 UTC by Philippe-Cholet

This was definitely simpler to implement than it was for `Combinations` (with vector items). The only difficulty is that it's recusive with a macro.

According to my notes, all iterators that should have a `size_hint` specialization now have. I like it.

The `count_ident` macro is moved to be available library-wide.

2023-09-27 17:00 UTC, Philippe-Cholet commented
@jswrenn Ooops... I missed that `checked_binomial` in `combinations.rs` is behind the `use_alloc` feature. Where should I move it? In `adaptors/mod.rs` I guess as it seems to be the easiest move?

2023-09-27 17:09 UTC, jswrenn commented
Yes, in adaptors/mod.rs is fine.

2023-09-28 19:36 UTC, jswrenn requested changes
For consistency, could you add a specialization test for this to `tests/specializations.rs`?

2023-09-28 20:24 UTC, jswrenn approved these changes

2023-09-28 20:25 UTC, merged