Test the laziness of our iterators
rust-itertools/itertools pull request #792
Opened 2023-11-03 09:37 UTC by Philippe-Cholet

Fixes #791
Add a test to:
- track iterators that are not lazy yet ;
- help track missing `must_use` attributes with very little discipline.

It's a long list of iterators and it has some edge cases. The error message help us understand how unlazy there are.

When `let _ = ...;` is not necessary, it indicates that a `must_use` attribute is missing.

CI will fail for some time.

2023-11-03 10:17 UTC, Philippe-Cholet commented
Currently:
- Load some items might be unavoidable, but surely not all.
  - `combinations(n)`, `permutations(n)` consume `n` items at definition (if `n != 0`).
  - `coalesce`, `dedup[_by][_with_count]`, `intersperse[_with]` consume 1 item at definition.
  - `tuple_combinations::<T>` consume `"T::len()" - 1` items at definition.
  - `kmerge[_by]` collect all items and consume the head of each iterator.
  - `iproduct!(i_1, i_2, i_n)` consumes the head of the first `n - 1` iterators.
- Missing `must_use` attributes(?): `combinations_with_replacement`, `multipeek`, `put_back`, `peek_nth`, `put_back_n`, `rciter`

2023-11-03 18:47 UTC, jswrenn requested changes
Tremendous thanks for doing this work! There's no rush on this (as we have some time to go before we can merge this PR), but before merging, I'd like us to have distinct tests, rather than one big one. We can do so without too much trouble with a little macro magic:
```rust
mod laziness {
    struct Panicking;

    impl Iterator for Panicking {
        type Item = ();
        fn next(&mut self) -> Option<()> {
            panic!("iterator adaptor is not lazy")
        }
    }
    
    macro_rules! tests {
        ($(test $name:ident { $body:expr })*) => {
            $(
                #[deny(unused_must_use)]
                #[test]
                fn $name() {
                    let _ = $body;
                }
            )*
        }
    }
    
    use itertools::*;
    
    tests! {
        test interleave {
            Panicking.interleave(Panicking)
        }
        
        test interleave_shortest {
            Panicking.interleave_shortest(Panicking)
        }
        
        test intersperse {
            Panicking.intersperse(())
        }
        
        /* and so on */
    }
}
```
The advantage of this approach is that the tests are run in parallel, are reported individually, and can be run individually.

2024-01-25 10:44 UTC, Philippe-Cholet commented
I'm not sure what to do about the remaining unlazy iterators yet.
I therefore added one commit to ignore the 3 failing laziness tests (then rebased).
I think we should merge this and un-ignore failing tests later.

2024-01-30 09:40 UTC, Philippe-Cholet commented
Quoting myself (see files) about `#[deny(unused_must_use)]`

> it does not protect us against removed `must_use` attributes.
> There is no simple way to test this yet.

One way would be to have a clippy lint `let_underscore_not_must_use` (or `unused_let_underscore` or unnecessary/unneeded) that would **lint useless `let _ =`**. It does not seem to exist yet (or I just did not find it?).

(_Creating a clippy lint `missing_iterator_fold` opened my eyes on this..._)

2024-02-06 22:28 UTC, jswrenn approved these changes

2024-02-06 22:41 UTC, merged