Document order guarantees for Itertools adapters.
rust-itertools/itertools pull request #822
Opened 2023-12-15 05:42 UTC by ryanavella

Address #819 by documenting the order guarantees for Itertools adapters.

2023-12-15 10:17 UTC, Philippe-Cholet commented
CI failed because rustfmt does not accept trailing spaces.

The question is if we want this guarantee to be library wide or limited to some adaptors like `Combinations`. I'll let @jswrenn decide on that.

2023-12-15 16:47 UTC, ryanavella commented
> The question is if we want this guarantee to be library wide or limited to some adaptors like Combinations. I'll let @jswrenn decide on that.

Ah yes, I hope I didn't misunderstand the conclusion from the other issue. I originally wanted a guarantee for Combination-like adapters, but I interpreted your comments as saying we don't intend to break iteration order for any adapters.

I could add a blanket "unless otherwise noted" clause, if there are specific adapters we'd like to leave open to further optimizations?

2023-12-19 15:54 UTC, jswrenn commented
Sorry for the misunderstanding. I don't think we can guarantee order for all adaptors, but I am okay guaranteeing it for the combinations adaptors.

2023-12-23 19:35 UTC, ryanavella commented
Thank you for the clarification, I've updated this PR so that the guarantee is only shown under `Itertools::combinations` and `Itertools::tuple_combinations`. Let me know if all looks good to you.

2024-01-09 16:38 UTC, Philippe-Cholet commented
@jswrenn What do you think of his formulation?

2024-01-09 16:39 UTC, jswrenn requested changes
Whoops, I had a draft review I thought I had posted. Thanks for the ping. It's just some minor nits.

2024-01-09 17:15 UTC, Philippe-Cholet commented
@ryanavella If you could commit jswrenn' suggestions and squash into a single commit, I would gladly merge this.

2024-01-10 11:27 UTC, Philippe-Cholet approved these changes

2024-01-11 16:28 UTC, Philippe-Cholet commented
@jswrenn My approval is not enough to get this merged.

2024-01-11 16:47 UTC, jswrenn approved these changes

2024-01-11 16:52 UTC, merged